version: '2'
services:
  ros-dev:
    image: osrf/ros:melodic-desktop-full
    container_name: ros-dev
    entrypoint:
      - /ros_entrypoint.sh
    command:
      - roscore
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw